# Create a Simple Neural Network #

In [1]:
import numpy as np

We are going to use sigmoid function as normalizing functions

In [8]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

Define input and output

In [3]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])
training_outputs = np.array([[0,1,1,0]]).T

In [4]:
np.random.seed(1)

Set initial weightage

In [6]:
# converting weights to a 3 by 1 matrix with values from -1 to 1 and mean of 0
synaptic_weights = 2 * np.random.random((3,1)) - 1
print('Initial random synaptic weights: ')
print(synaptic_weights)

Initial random synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [7]:
for iteration in range(1):
    input_layer = training_inputs
    output = sigmoid(np.dot(input_layer, synaptic_weights))
    
print('Output after first iteration: ')
print(output)

Output after first iteration: 
[[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]


Training process:
1. Take the inputs from the training example, put them through formula to get output
2. Calculate error between output and actual output
3. Adjust weights accordingly
4. Repeat

In [9]:
for iteration in range(20000):
    input_layer = training_inputs
    output = sigmoid(np.dot(input_layer, synaptic_weights))
    error = training_outputs - output
    adjustment = error * sigmoid_derivative(output)
    synaptic_weights += np.dot(input_layer.T, adjustment)
    
print('Synaptic weights after 20000 iterations: ')
print(synaptic_weights)
print('Output after 20000 iterations: ')
print(output)

Synaptic weights after 20000 iterations: 
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Output after 20000 iterations: 
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]


# Create a workable class #

In [16]:
import numpy as np

class NeuralNetwork():
    
    def __init__(self):
        np.random.seed(1)
        self.synaptic_weights = 2 * np.random.random((3,1)) - 1
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, x):
        return x * (1 - x)
    
    def think(self, inputs):
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        return output
    
    def train(self, training_inputs, training_outputs, training_iterations):
        for iteration in range(training_iterations):
            output = self.think(training_inputs)
            error = training_outputs - output
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))
            self.synaptic_weights += adjustments

In [21]:
neural_network = NeuralNetwork()
print('Random synaptic weights: ')
print(neural_network.synaptic_weights)
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])
training_outputs = np.array([[0,1,1,0]]).T
neural_network.train(training_inputs, training_outputs, 20000)
print("Synaptic weights after training: ")
print(neural_network.synaptic_weights)
A = str(input("Input 1: "))
B = str(input("Input 2: "))
C = str(input("Input 3: "))
print("New situation, input data = ", A, B, C)
print("Output data = ")
print(neural_network.think(np.array([A, B, C])))    

Random synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptic weights after training: 
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Input 1: 0
Input 2: 1
Input 3: 1
New situation, input data =  0 1 1
Output data = 
[0.005536]
